DEFAULT:
 ENVIRONMENT: local
 HOSTNAME: http://localhost
 LOGGING_LEVEL:	1
DEV:
 ENVIRONMENT: dev
 HOSTNAME: 
 LOGGING_LEVEL:	1
QA:
 ENVIRONMENT: qa
 HOSTNAME: 
 LOGGING_LEVEL:	1
UAT:
 ENVIRONMENT: uat
 HOSTNAME: 
 LOGGING_LEVEL: 1
PROD:
 ENVIRONMENT: prod
 HOSTNAME: 
 LOGGING_LEVEL: 4