/**
 * Auth action types
 */
export const GET_ALL_CLAIMS = "GET_ALL_CLAIMS";
export const USER_FEEDBACK_SUBMIT = "USER_FEEDBACK_SUBMIT";
export const USER_FEEDBACK_RESPONSE = "USER_FEEDBACK_RESPONSE";
export const GET_CLAIM_DATA = "GET_CLAIM_DATA";
export const CHANGE_SORT_DIRECTION = "CHANGE_SORT_DIRECTION";
export const RESET_DIALOG_DATA = "RESET_DIALOG_DATA";